In [1]:
# extracting DXY data from yahoo finance

In [1]:
import pandas as pd

In [2]:
!pip install yfinance

Collecting yfinance
  Downloading yfinance-1.6.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /opt/anaconda3/envs/bitcoin_tf/lib/python3.12/site-packages (from yfinance) (4.15.0)
Collecting curl_cffi>=0.15 (from yfinance)
  Downloading curl_cffi-0.16.1-cp310-abi3-macosx_11_0_arm64.whl.metadata (17 kB)
Collecting lxml>=4.9.0 (from yfinance)
  Downloading lxml-6.1.2-cp312-cp312-macosx_10_13_universal2.whl.metadata (3.3 kB)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/envs/bitcoin_tf/lib/python3.12/site-packages (from yfinance) (1.26.4)
Requirement already satisfied: pandas>=1.3.0 in /opt/anaconda3/envs/bitcoin_tf/lib/python3.12/site-packages (from yfinance) (3.0.5)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: platformdirs>=2.0.0 in /opt/anaconda3/envs/bitcoin_tf/lib/python3.12/site-packages (from yfinance) (4.11.3)
Requirement already satisfied: protobuf>=3.19.0 in /opt/anaconda3/envs/bitcoin_tf/lib/python3.12/site-packages (from yfinance) (4.25.9)
Collecting pytz>=2022.5 (from yfinance)
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: requests>=2.31 in /opt/anaconda3/envs/bitcoin_tf/lib/python3.12/site-packages (from yfinance) (2.34.2)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-17.0.1-cp312-cp312-macosx_11_0_arm64.whl.metadata (6.3 kB)
Requirement already satisfied: soupsieve>=1.6.1 in /opt/anaconda3/envs/bitcoin_tf/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /opt/anaconda3/envs/bitcoin_tf/lib/python3.12/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/anaconda3/envs/bitcoin_tf/lib/python3.12/site-packages (from curl_cffi>=0.15->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2024.2.2 in /opt/anaconda3/envs/bitcoin_tf/lib/python3.12/site-packages (from curl_cffi>=0.15->yfinance) (2026.7.22)
Requirement already satisfied: pycparser in /opt/anaconda3/envs/bitcoin_tf/lib/python3.12/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/bitcoin_tf/lib/python3.12/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/bitcoin_tf/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/envs/bitcoin_tf/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/envs/bitcoin_tf/lib/python3.12/site-packages (from requests>=2.31->yfinance) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/anaconda3/envs/bitcoin_tf/lib/python3.12/site-packages (from requests>=2.31->yfinance) (2.7.0)
Downloading yfinance-1.6.0-py3-none-any.whl (148 kB)
Downloading curl_cffi-0.16.1-cp310-abi3-macosx_11_0_arm64.whl (2.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 8.2 MB/s  0:00:007.4 MB/s eta 0:00:01
Downloading lxml-6.1.2-cp312-cp312-macosx_10_13_universal2.whl (8.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 6.9 MB/s  0:00:01a 0:00:01m eta 0:00:01
Downloading multitasking-0.0.13-py3-none-any.whl (16 kB)
Downloading peewee-4.4.0-py3-none-any.whl (191 kB)
Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
Downloading websockets-17.0.1-cp312-cp312-macosx_11_0_arm64.whl (210 kB)
Installing collected packages: pytz, multitasking, websockets, peewee, lxml, curl_cffi, yfinance
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [yfinance]━━ 6/7 [yfinance]rl_cffi]
Successfully installed curl_cffi-0.16.1 lxml-6.1.2 multitasking-0.0.13 peewee-4.4.0 pytz-2026.3.post1 websockets-17.0.1 yfinance-1.6.0

In [4]:
import yfinance as yf

dxy = yf.download(
    "DX-Y.NYB",
    start="2017-12-31",
    end="2026-08-22",
    interval="1d"
)

print(dxy.head())
print(dxy.tail())

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open   Volume
Ticker       DX-Y.NYB   DX-Y.NYB   DX-Y.NYB   DX-Y.NYB DX-Y.NYB
Date
2018-01-02  91.849998  92.250000  91.750000  92.239998        0
2018-01-03  92.160004  92.260002  91.809998  91.820000        0
2018-01-04  91.849998  92.260002  91.800003  92.220001        0
2018-01-05  91.949997  92.099998  91.779999  91.870003        0
2018-01-08  92.330002  92.400002  91.879997  92.059998        0
Price           Close       High        Low       Open   Volume
Ticker       DX-Y.NYB   DX-Y.NYB   DX-Y.NYB   DX-Y.NYB DX-Y.NYB
Date
2026-08-17  99.639999  99.669998  99.290001  99.660004        0
2026-08-18  99.650002  99.690002  99.519997  99.540001        0
2026-08-19  98.830002  99.690002  98.769997  99.669998        0
2026-08-20  98.900002  98.930000  98.559998  98.839996        0
2026-08-21  98.800003  98.910004  98.559998  98.800003        0

In [5]:
dxy.to_csv("DXY.csv")

In [6]:
dxy = pd.read_csv("DXY.csv", header=[0, 1])

print(dxy.head())
print(dxy.shape)

        Price      Close       High        Low       Open   Volume
       Ticker   DX-Y.NYB   DX-Y.NYB   DX-Y.NYB   DX-Y.NYB DX-Y.NYB
0        Date        NaN        NaN        NaN        NaN      NaN
1  2018-01-02  91.849998  92.250000  91.750000  92.239998      0.0
2  2018-01-03  92.160004  92.260002  91.809998  91.820000      0.0
3  2018-01-04  91.849998  92.260002  91.800003  92.220001      0.0
4  2018-01-05  91.949997  92.099998  91.779999  91.870003      0.0
(2174, 6)

In [7]:
# removing the unnecesssary columns

In [8]:
import pandas as pd

# Read the CSV
dxy = pd.read_csv("DXY.csv", header=[0, 1])

# Remove the extra first row containing "Date"
dxy = dxy.iloc[1:].copy()

# Create clean dataframe using Date + Close
dxy_clean = pd.DataFrame({
    'Date': pd.to_datetime(dxy[('Price', 'Ticker')]),
    'DXY': pd.to_numeric(dxy[('Close', 'DX-Y.NYB')], errors='coerce')
})

# Remove missing values
dxy_clean = dxy_clean.dropna().reset_index(drop=True)

print(dxy_clean.head())
print(dxy_clean.tail())
print(dxy_clean.shape)

        Date        DXY
0 2018-01-02  91.849998
1 2018-01-03  92.160004
2 2018-01-04  91.849998
3 2018-01-05  91.949997
4 2018-01-08  92.330002
           Date        DXY
2168 2026-08-17  99.639999
2169 2026-08-18  99.650002
2170 2026-08-19  98.830002
2171 2026-08-20  98.900002
2172 2026-08-21  98.800003
(2173, 2)

In [9]:
dxy_clean.to_csv("DXY_clean.csv")

In [10]:
dxy = pd.read_csv("DXY.csv", header=[0, 1])

dxy_clean = pd.DataFrame({
    'Date': pd.to_datetime(dxy[('Price', 'Ticker')], errors='coerce'),
    'DXY': pd.to_numeric(dxy[('Close', 'DX-Y.NYB')], errors='coerce')
})

dxy_clean = dxy_clean.dropna().reset_index(drop=True)

print(dxy_clean.head())
print(dxy_clean.shape)
print(dxy_clean['Date'].min())
print(dxy_clean['Date'].max())

ERROR! Session/line number was not unique in database. History logging moved to new session 27
        Date        DXY
0 2018-01-02  91.849998
1 2018-01-03  92.160004
2 2018-01-04  91.849998
3 2018-01-05  91.949997
4 2018-01-08  92.330002
(2173, 2)
2018-01-02 00:00:00
2026-08-21 00:00:00

/var/folders/b_/z2kb62v568gcwpkqj2cntwh40000gn/T/ipykernel_83971/1601791961.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  'Date': pd.to_datetime(dxy[('Price', 'Ticker')], errors='coerce'),

In [11]:
print("Start:", dxy_clean['Date'].min())
print("End:", dxy_clean['Date'].max())

print("\nMissing values:")
print(dxy_clean.isna().sum())

Start: 2018-01-02 00:00:00
End: 2026-08-21 00:00:00

Missing values:
Date    0
DXY     0
dtype: int64

In [12]:
vix = yf.download('^VIX', start='2018-01-01', end='2026-08-22', auto_adjust=False)
sp500 = yf.download('^GSPC', start='2018-01-01', end='2026-08-22', auto_adjust=False)
gold = yf.download('GC=F', start='2018-01-01', end='2026-08-22', auto_adjust=False)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [13]:
print("VIX:", vix.shape)
print("S&P500:", sp500.shape)
print("Gold:", gold.shape)

display(vix.head())
display(sp500.head())
display(gold.head())

VIX: (2172, 6)
S&P500: (2171, 6)
Gold: (2172, 6)

Price      Adj Close Close   High   Low   Open Volume
Ticker          ^VIX  ^VIX   ^VIX  ^VIX   ^VIX   ^VIX
Date
2018-01-02      9.77  9.77  11.07  9.52  10.95      0
2018-01-03      9.15  9.15   9.65  8.94   9.56      0
2018-01-04      9.22  9.22   9.31  8.92   9.01      0
2018-01-05      9.22  9.22   9.54  9.00   9.10      0
2018-01-08      9.52  9.52   9.89  9.32   9.61      0

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,^GSPC,^GSPC,^GSPC,^GSPC,^GSPC,^GSPC
Date,,,,,,
2018-01-02,2695.810059,2695.810059,2695.889893,2682.360107,2683.729980,3397430000
2018-01-03,2713.060059,2713.060059,2714.370117,2697.770020,2697.850098,3544030000
2018-01-04,2723.989990,2723.989990,2729.290039,2719.070068,2719.310059,3697340000
2018-01-05,2743.149902,2743.149902,2743.449951,2727.919922,2731.330078,3239280000
2018-01-08,2747.709961,2747.709961,2748.510010,2737.600098,2742.669922,3246160000

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,GC=F,GC=F,GC=F,GC=F,GC=F,GC=F
Date,,,,,,
2018-01-02,1313.699951,1313.699951,1317.599976,1302.300049,1302.300049,68
2018-01-03,1316.199951,1316.199951,1320.099976,1312.099976,1320.000000,42
2018-01-04,1319.400024,1319.400024,1322.000000,1319.400024,1319.400024,2
2018-01-05,1320.300049,1320.300049,1320.300049,1320.300049,1320.300049,1
2018-01-08,1318.599976,1318.599976,1319.900024,1314.599976,1319.900024,41

In [14]:
print(vix.index.min(), vix.index.max())
print(sp500.index.min(), sp500.index.max())
print(gold.index.min(), gold.index.max())

2018-01-02 00:00:00 2026-08-21 00:00:00
2018-01-02 00:00:00 2026-08-21 00:00:00
2018-01-02 00:00:00 2026-08-21 00:00:00

In [15]:
# clean the data

In [18]:
vix = vix.reset_index()
sp500 = sp500.reset_index()
gold = gold.reset_index()

vix = vix[['Date','Close']].rename(columns={'Close':'VIX'})
sp500 = sp500[['Date','Close']].rename(columns={'Close':'SP500'})
gold = gold[['Date','Close']].rename(columns={'Close':'Gold'})

for x in [vix, sp500, gold]:
    x['Date'] = pd.to_datetime(x['Date']).dt.tz_localize(None)

print(vix.head())
print(sp500.head())
print(gold.head())

        Date   VIX
0 2018-01-02  9.77
1 2018-01-03  9.15
2 2018-01-04  9.22
3 2018-01-05  9.22
4 2018-01-08  9.52
        Date        SP500
0 2018-01-02  2695.810059
1 2018-01-03  2713.060059
2 2018-01-04  2723.989990
3 2018-01-05  2743.149902
4 2018-01-08  2747.709961
        Date         Gold
0 2018-01-02  1313.699951
1 2018-01-03  1316.199951
2 2018-01-04  1319.400024
3 2018-01-05  1320.300049
4 2018-01-08  1318.599976

In [19]:
vix.to_csv('VIX.csv', index=False)
sp500.to_csv('SP500.csv', index=False)
gold.to_csv('Gold.csv', index=False)

print("CSV files saved successfully.")

CSV files saved successfully.

In [20]:
vix.to_csv('VIX.csv', index=False)